#volumes:
#  static:
#  db-data:

services:
  db:
    image: postgres:18
    ports:
      - 5432:5432
#    volumes:
#      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 6
  backend:
    image: danteonline/python-base-2025-05
    build:
      context: .
    ports:
      - 8000:8000
#    volumes:
#      - static:/static/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_HOST: "db"
    command: bash -c "
      poetry run python manage.py migrate
      && poetry run gunicorn config.wsgi -b 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy
