version: "3"

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: user
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d shop -U user"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    image: danteonline/basepython-2023-11
    build:
      dockerfile: ./build/Dockerfile
      context: ./
#    entrypoint:
#      - bash
#      - "entrypoint.sh"
#    command:
#      - flask
#      - run
#      - "--host=0.0.0.0"
    environment:
      SQLALCHEMY_DATABASE_URI: "postgresql+psycopg://user:example@pg:5432/shop"
    ports:
      - "5000:80"
    depends_on:
      pg:
        condition: service_healthy


#volumes:
#  db-data:
