#volumes:
#  static:
#  db-data:

services:
  db:
    # restart: always
    image: postgres:14.2
    expose:
      - "5432"
#    volumes:
#      - db-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 6
  backend:
    # restart: always
    image: danteonline/base-python-2022-07
    ports:
      - "8000:8000"
#    volumes:
#      - static:/static/
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      DB_HOST: "${DB_HOST}"
    command: bash -c "
      poetry run python manage.py migrate
      && poetry run python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy