services:
  app:
    build:
      context: .
      dockerfile: ./docker-build/app/Dockerfile
    command:
      - gunicorn
      - --workers=2
      - --worker-class=uvicorn.workers.UvicornWorker
      - --bind=0.0.0.0:8000
      - main:app
    environment:
      BLOG_APP__DB__SQLA__ECHO: 0
      BLOG_APP__DB__PG__HOST: pg
      BLOG_APP__DB__PG__PORT: 5432
      BLOG_APP__DB__PG__DB: ${PG_DB}
      BLOG_APP__DB__PG__USER: ${PG_USER}
      BLOG_APP__DB__PG__PASSWORD: ${PG_PASSWORD}
    ports:
      - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:18
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /var/lib/postgresql/18/docker
    volumes:
      - pg_data:/var/lib/postgresql/18/docker
#    ports:
#      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 3s
      timeout: 2s
      retries: 3

volumes:
  pg_data:
